In [1]:
"""
Foundings:

type mismatches:
    salary -> int
    created_at -> datetime
    deadline_at -> datetime
    view_count -> int after parsing 
    
6 nulls in deadline_at column, these are outdated listings that out of the main scrape range. Drop during cleaning.
"Company" placeholder in company name column. Valid listings, but replace with null to not bias company-based analysis
almost 70 percent of salary column is 0, convert to null
every value in direct_apply is 0, drop the column
id, company_id, url, fetched_at is irrelevant to the purpose of this analysis, drop these columns.
description needs extraction
"""

'\nFoundings:\n\ntype mismatches:\n    salary -> int\n    created_at -> datetime\n    deadline_at -> datetime\n    view_count -> int after parsing \n\n6 nulls in deadline_at column, these are outdated listings that out of the main scrape range. Drop during cleaning.\n"Company" placeholder in company name column. Valid listings, but replace with null to not bias company-based analysis\nalmost 70 percent of salary column is 0, convert to null\nevery value in direct_apply is 0, drop the column\nid, company_id, url, fetched_at is irrelevant to the purpose of this analysis, drop these columns.\ndescription needs extraction\n'

In [2]:
import pandas as pd

from jobanalysis.paths import RAW_DATA
from jobanalysis.io import load

In [3]:
df = load(RAW_DATA)

df.head()

      id  ...           fetched_at
0  85507  ...  2026-05-04 18:11:57
1  85668  ...  2026-05-04 18:11:57
2  86834  ...  2026-05-04 18:11:57
3  86880  ...  2026-05-04 18:11:57
4  87172  ...  2026-05-04 18:11:57

[5 rows x 13 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3998 entries, 0 to 3997
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            3998 non-null   int64
 1   title         3998 non-null   str
 2   company       3998 non-null   str
 3   company_id    3998 non-null   int64
 4   salary        3998 non-null   str
 5   category      3998 non-null   str
 6   created_at    3998 non-null   str
 7   deadline_at   3992 non-null   str
 8   view_count    3998 non-null   object
 9   direct_apply  3998 non-null   int64
 10  url           3998 non-null   str
 11  description   3998 non-null   str
 12  fetched_at    3998 non-null   str
dtypes: int64(3), object(1), str(9)
memory usage: 406.2+ KB

In [5]:
df.isna().sum()

id              0
title           0
company         0
company_id      0
salary          0
category        0
created_at      0
deadline_at     6
view_count      0
direct_apply    0
url             0
description     0
fetched_at      0
dtype: int64

In [6]:
df.describe()

                  id     company_id  direct_apply
count    3998.000000    3998.000000        3998.0
mean   138468.795148   40723.479240           0.0
std      2236.658382   48510.247856           0.0
min     85507.000000      16.000000           0.0
25%    137452.250000    3944.000000           0.0
50%    138544.500000    7252.000000           0.0
75%    139636.750000   78886.000000           0.0
max    140698.000000  140680.000000           0.0

In [7]:
df["company"].value_counts()

company
Company                                        132
Azərmemarlayihə Dövlət Baş Layihə İnstitutu     92
Kontakt Home                                    76
IRES                                            48
PASHA Bank                                      38
                                              ...
Grandmoto                                        1
Best Soft                                        1
Bakı Dövlət Layihə İnsitutu                      1
Smart Audit                                      1
RoarAds                                          1
Name: count, Length: 1197, dtype: int64

In [8]:
df[df["company"] == "Company"].head()

         id  ...           fetched_at
6    136337  ...  2026-05-04 18:11:57
15   136347  ...  2026-05-04 18:11:57
111  136452  ...  2026-05-04 18:11:57
113  136454  ...  2026-05-04 18:11:57
117  136461  ...  2026-05-04 18:11:57

[5 rows x 13 columns]

In [9]:
df["salary"] = df["salary"].astype(int)
(df["salary"] == 0).sum() / len(df)

np.float64(0.7021010505252626)

In [10]:
df["direct_apply"].value_counts()

direct_apply
0    3998
Name: count, dtype: int64

In [11]:
df["view_count"].apply(type).value_counts()

view_count
<class 'int'>    3827
<class 'str'>     171
Name: count, dtype: int64

In [12]:
df["category"].value_counts()

category
Inzibati, Biznes və İdarəetmə                    797
Maliyyə xidmətləri                               663
Mühəndislik                                      543
Pərakəndə satış və müştəri xidmətləri            409
Komputerləşmə və İKT                             291
Nəqliyyat, paylama və logistika                  225
Marketinq, reklam, çap və nəşriyyat              223
Otel, İaşə, Turizm                               201
Təlim və tədris                                  166
Təsərrüfat və əmlak xidmətləri                    86
Hüquq və məhkəmə xidmətləri                       67
İstehsalat                                        65
İnşaat və tikinti                                 59
Dizayn, incəsənət və sənətkarlıq                  58
Səhiyyə                                           54
Təhlükəsizlik, uniforma və qoruyucu xidmətlər     41
Memarlıq                                          31
İfaçılıq sənəti və media                          18
Dillər                                             1
Name: count, dtype: int64

In [13]:
pd.to_datetime(df["created_at"]).agg(["min", "max"])

min   2024-09-03 00:00:00+04:00
max   2026-05-20 00:00:00+04:00
Name: created_at, dtype: datetime64[us, UTC+04:00]